### ISSUE TITLE
Invalid value in searchCursor

### ISSUE THREAD

**Issue by sidati** [fullcontact/contacts-api-node#4]
Hello,
After i get the results of **contacts search request**, i try to use the `searchScroll` to fetch the next page, but instead i get `Invalid value in searchCursor` error.

```js
  const page1 = await FC.contacts.contacts.search(auth.access_token, query);
  console.log('1st page : ', page1.contacts.length);

  if (res.hasOwnProperty('cursor')) {
    const page2 = await FC.contacts.contacts.search(auth.access_token, {
      ...query,
      searchCursor: res.cursor
    });

    console.log('2nd Page : ', page2.contacts.length);
  }
```

This is the **searchCursor** format when i log it :  `-1982292599,-1817101551,2691`, the [doc show another format](https://api.fullcontact.com/api/v1/docs/methods/contacts.search).

How can i fix this ??
Thanks

**Comment by mattdelliott** [comment]
@sidati Sorry you're having trouble with the `searchCursor`. I believe it should be a SHA1 hash. We'll look into why it's coming back like that and get back to you.

**Comment by mattdelliott** [comment]
@sidati this issue should be resolved. Any of the searchCursors you have that look like the format above will not work, but new responses should contain a hash for the cursor and those should work just fine. Let us know if you have any other questions or issues.
